spring:
#  datasource:
##    url:  jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name : org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://java-web-db.c1ukcaym4bjl.ap-northeast-2.rds.amazonaws.com
    username: eedo
    password: david100894!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql : true

    logging_level:
      org.hibernate.SQL: debug
#      org.hibernate.type : trace

