spring:
  datasource:
    url: jdbc:mysql://java-web-db-2.c1ukcaym4bjl.ap-northeast-2.rds.amazonaws.com:3306/java_web_db
    username: eedo
    password: david100894!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    logging_level:
      org.hibernate.SQL: debug
